# Jonathan Realmuto
# Promt
PS1='\[\e]0;\w\a\]\n\[\e[32m\]\u\[\e[30m\]|\[\e[34m\]\h: \[\e[33m\]\w\[\e[31m\]\n\$ \[\e[30m\]'

# Path
PATH=/usr/local/bin:$PATH

# ls colors
export LS_OPTIONS='--color=auto'
eval "`dircolors`"
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'

# Alias
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias mkdir="mkdir -pv"

# ROS
source /opt/ros/kinetic/setup.bash
