#!/bin/bash

# Device tree overlay compile script

DEVICE_TREE=anklebot-00A0

echo -n "Building device tree ..."

dtc -O dtb -o $DEVICE_TREE.dtbo -b 0 -@ $DEVICE_TREE.dts

echo "Copying to /lib/firmware "

rm -f /lib/firmware/$DEVICE_TREE.dtbo

cp -f ./$DEVICE_TREE.dtbo /lib/firmware/$DEVICE_TREE.dtbo
