#!/bin/sh -e
# /etc/init.d/wifi-up
#
### BEGIN INIT INFO
# Jonathan Realmuto
# Provides:          wifi-up.sh
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Auto-wifi.
# Description:       This script enables wlan0. Should be called at boot.
### END INIT INFO

echo 'Starting wifi ...'
ifdown -v wlan0
ifup -v wlan0
echo 'Wifi should be up now, exiting.'

echo 'Setting time now ...'
service ntp stop
ntpdate -s us.pool.ntp.org
service ntp start
date
echo 'Date should be correct now.'
